webtalk_init -webtalk_dir C:/Users/KY/Desktop/Sc 2019/CG3207/lab2/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/cond_logic_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 25 21:57:11 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7cf10f7a-f875-484b-88a4-6918aeecf2d0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7af3b5b5600f43b0b6379cb2b6d53cd9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5896_KB" -context "xsim\\usage"
webtalk_transmit -clientid 599847992 -regid "" -xml C:/Users/KY/Desktop/Sc 2019/CG3207/lab2/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/cond_logic_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/KY/Desktop/Sc 2019/CG3207/lab2/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/cond_logic_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/KY/Desktop/Sc 2019/CG3207/lab2/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/cond_logic_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
